<template>
  <div class="space-y-6 max-w-[90rem] mx-auto px-4 pb-12">
    <div class="text-center">
      <h1 class="text-3xl font-extrabold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-green-400 to-emerald-600">Optimization Complete</h1>
      <p class="text-dark-400 mt-2">Here is the mathematically optimal squad generated by AI</p>
    </div>

    <!-- Stats Bar -->
    <div v-if="results" class="bg-dark-800 p-4 rounded-xl border border-dark-700 flex justify-around text-center shadow-lg">
      <div>
        <div class="text-sm text-dark-400 font-bold uppercase tracking-wider">Total Credits</div>
        <div class="text-2xl font-black text-white">{{ totalCredits }} / 100</div>
      </div>
      <div>
        <div class="text-sm text-dark-400 font-bold uppercase tracking-wider">Projected Points</div>
        <div class="text-2xl font-black text-brand">{{ totalPoints.toFixed(1) }}</div>
      </div>
      <div>
        <div class="text-sm text-dark-400 font-bold uppercase tracking-wider">Solver Status</div>
        <div class="text-2xl font-black text-green-400">{{ results.status }}</div>
      </div>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start my-8">
      <!-- Pitch Visualization -->
      <div class="relative w-full aspect-[4/5] bg-green-900 rounded-[40px] border-[12px] border-green-800 overflow-hidden shadow-2xl shadow-green-900/50">
      <div class="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/grass.png')] opacity-30 mix-blend-overlay"></div>
      
      <!-- Pitch Lines -->
      <div class="absolute inset-y-12 inset-x-12 border-2 border-white/30 rounded-[200px]"></div>
      
      <div class="absolute inset-0 flex flex-col justify-between py-16 px-4">
        
        <!-- Wicket Keepers -->
        <div class="flex justify-center space-x-4">
          <PlayerIcon v-for="p in getPlayersByRole('WK')" :key="p.id" :player="p" @click="openSwapModal(p)" />
        </div>
        
        <!-- Batters -->
        <div class="flex justify-center space-x-6 flex-wrap gap-y-4">
          <PlayerIcon v-for="p in getPlayersByRole('BAT')" :key="p.id" :player="p" @click="openSwapModal(p)" />
        </div>
        
        <!-- All Rounders -->
        <div class="flex justify-center space-x-8">
          <PlayerIcon v-for="p in getPlayersByRole('AR')" :key="p.id" :player="p" @click="openSwapModal(p)" />
        </div>
        
        <!-- Bowlers -->
        <div class="flex justify-center space-x-6 flex-wrap gap-y-4">
          <PlayerIcon v-for="p in getPlayersByRole('BOWL')" :key="p.id" :player="p" @click="openSwapModal(p)" />
        </div>

      </div>
    </div>

    <!-- AI Insights Panel -->
    <div class="bg-gradient-to-br from-dark-800 to-dark-900 rounded-3xl border border-brand/30 shadow-[0_0_30px_rgba(255,76,41,0.15)] overflow-hidden relative">
      <div class="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-brand to-orange-500"></div>
      <div class="p-6 md:p-8">
        <h2 class="text-2xl font-black mb-4 flex items-center justify-between">
          <div class="flex items-center space-x-3">
            <div class="w-8 h-8 rounded bg-gradient-to-br from-brand to-orange-500 flex items-center justify-center text-white text-sm">✨</div>
            <span class="bg-clip-text text-transparent bg-gradient-to-r from-white to-gray-400">AI Scout Report</span>
          </div>
          <button v-if="squadChanged" @click="fetchInsights" class="text-xs font-bold px-3 py-1.5 rounded-lg bg-brand hover:bg-brand-hover text-white transition-colors flex items-center space-x-1 shadow-lg shadow-brand/20 animate-pulse">
            <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"></path></svg>
            <span>Regenerate Report</span>
          </button>
        </h2>
        
        <div v-if="isLoadingInsights" class="space-y-4 animate-pulse">
          <div class="h-4 bg-dark-700 rounded w-3/4"></div>
          <div class="h-4 bg-dark-700 rounded w-full"></div>
          <div class="h-4 bg-dark-700 rounded w-5/6"></div>
          <div class="h-4 bg-dark-700 rounded w-2/3 mt-6"></div>
          <div class="text-brand/60 text-sm mt-4 font-mono font-bold flex items-center space-x-2">
            <svg class="animate-spin w-4 h-4" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" class="opacity-25"></circle><path fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" class="opacity-75"></path></svg>
            <span>Analyzing matchups and simulating pitch conditions...</span>
          </div>
        </div>
        
        <div v-else-if="insightsError" class="text-red-400 font-medium bg-red-500/10 p-4 rounded-xl border border-red-500/20">
          {{ insightsError }}
        </div>
        
        <div v-else class="prose prose-invert prose-brand max-w-none text-gray-300">
          <!-- We use v-html or just render markdown if we have a parser. For now, white-space: pre-wrap -->
          <div class="whitespace-pre-wrap font-medium leading-relaxed" v-html="formattedInsights"></div>
        </div>
      </div>
    </div>
    </div> <!-- End of Grid -->

    <div class="flex justify-center space-x-4 pt-4">
      <router-link to="/draft" class="px-8 py-3 bg-dark-800 hover:bg-dark-700 text-white rounded-full font-bold transition-all border border-dark-600">Edit Draft</router-link>
      <router-link to="/" class="px-8 py-3 bg-brand hover:bg-brand-hover text-white rounded-full font-bold transition-all shadow-lg shadow-brand/30">Start New Draft</router-link>
    </div>

    <!-- Swap Modal -->
    <div v-if="selectedPlayerForSwap" class="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div class="absolute inset-0 bg-black/80 backdrop-blur-sm" @click="selectedPlayerForSwap = null"></div>
      <div class="bg-dark-800 rounded-3xl border border-dark-600 shadow-2xl relative z-10 w-full max-w-lg overflow-hidden">
        <div class="p-6 border-b border-dark-700 flex justify-between items-center">
          <h3 class="text-xl font-bold text-white">Player Options</h3>
          <button @click="selectedPlayerForSwap = null" class="text-gray-400 hover:text-white text-2xl leading-none">&times;</button>
        </div>
        <div class="p-6 bg-dark-900/50">
          <!-- Role Assignment -->
          <div class="mb-6">
            <h4 class="text-sm font-bold text-gray-400 uppercase tracking-wider mb-3">Assign Role</h4>
            <div class="flex space-x-3">
              <button @click="assignCaptain(selectedPlayerForSwap)" :class="selectedPlayerForSwap.is_captain ? 'bg-orange-500 border-orange-400 shadow-lg shadow-orange-500/20' : 'bg-dark-800 border-dark-600 hover:border-orange-500'" class="flex-1 py-3 px-4 rounded-xl border font-bold text-white transition-all text-sm flex flex-col items-center">
                <span class="text-lg mb-1">👑</span> Captain (2x Pts)
              </button>
              <button @click="assignViceCaptain(selectedPlayerForSwap)" :class="selectedPlayerForSwap.is_vice_captain ? 'bg-blue-600 border-blue-400 shadow-lg shadow-blue-500/20' : 'bg-dark-800 border-dark-600 hover:border-blue-500'" class="flex-1 py-3 px-4 rounded-xl border font-bold text-white transition-all text-sm flex flex-col items-center">
                <span class="text-lg mb-1">⭐</span> Vice-Captain (1.5x)
              </button>
            </div>
          </div>
          
          <h4 class="text-sm font-bold text-gray-400 uppercase tracking-wider mb-3">Swap Player</h4>
          <p class="text-xs text-gray-500 mb-4">Select a benched player to replace <span class="font-bold text-brand">{{ selectedPlayerForSwap.name }}</span></p>
          <div class="space-y-3 max-h-[60vh] overflow-y-auto pr-2">
            <div v-for="bp in benchedPlayers" :key="bp.id" 
                 class="flex items-center justify-between p-3 rounded-xl border transition-colors"
                 :class="canSwapIn(bp) ? 'bg-dark-800 border-dark-600 hover:border-brand cursor-pointer' : 'bg-dark-900 border-red-900/30 opacity-50 cursor-not-allowed'"
                 @click="canSwapIn(bp) && performSwap(bp)">
              <div class="flex items-center space-x-3">
                <img :src="bp.image" class="w-10 h-10 rounded-full bg-dark-900 border border-dark-700" onerror="this.src='https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/User_icon_2.svg/2048px-User_icon_2.svg.png'" />
                <div>
                  <div class="font-bold text-white text-sm">{{ bp.name }} <span v-if="bp.is_foreign" class="text-xs">✈️</span></div>
                  <div class="text-[10px] text-gray-400 font-medium tracking-wide">{{ bp.team }} • {{ bp.role }} • {{ bp.form_avg_runs }}R {{ bp.form_avg_wickets }}W</div>
                </div>
              </div>
              <div class="font-black text-brand text-sm">{{ bp.credits }} CR</div>
            </div>
            <div v-if="benchedPlayers.length === 0" class="text-center text-gray-500 py-8">No benched players available.</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useDraftStore } from '../store/draftStore'
import PlayerIcon from '../components/PlayerIcon.vue'

const router = useRouter()
const store = useDraftStore()
const results = ref<any>(null)

const isLoadingInsights = ref(true)
const insightsReport = ref('')
const insightsError = ref('')
const squadChanged = ref(false)

// Swap Logic State
const selectedPlayerForSwap = ref<any>(null)

const benchedPlayers = computed(() => {
  if (!results.value || !store.draftedPlayers) return []
  return store.draftedPlayers.filter(dp => !results.value.squad.find((s: any) => s.id === dp.id))
})

const openSwapModal = (player: any) => {
  selectedPlayerForSwap.value = player
}

const canSwapIn = (bp: any) => {
  if (!selectedPlayerForSwap.value) return false
  
  // Create simulated squad
  const simSquad = results.value.squad.filter((p: any) => p.id !== selectedPlayerForSwap.value.id)
  simSquad.push(bp)
  
  // 1. Credits limit
  const credits = simSquad.reduce((sum: number, p: any) => sum + p.credits, 0)
  if (credits > 100) return false
  
  // 2. Team limit (max 7 per team)
  const teamCount = simSquad.filter((p: any) => p.team === bp.team).length
  if (teamCount > 7) return false
  
  // 3. Foreign limit (max 4 per team)
  const teamForeignCount = simSquad.filter((p: any) => p.team === bp.team && p.is_foreign).length
  if (teamForeignCount > 4) return false
  
  // 4. Role limits
  const wk = simSquad.filter((p: any) => p.role === 'WK').length
  const bat = simSquad.filter((p: any) => p.role === 'BAT').length
  const ar = simSquad.filter((p: any) => p.role === 'AR').length
  const bowl = simSquad.filter((p: any) => p.role === 'BOWL').length
  
  if (wk < 1 || wk > 4) return false
  if (bat < 3 || bat > 6) return false
  if (ar < 1 || ar > 4) return false
  if (bowl < 3 || bowl > 6) return false
  
  return true
}

const performSwap = (bp: any) => {
  if (!selectedPlayerForSwap.value) return
  
  const index = results.value.squad.findIndex((p: any) => p.id === selectedPlayerForSwap.value.id)
  if (index !== -1) {
    results.value.squad[index] = bp
    
    // We need a quick mock of predicted_points for the swapped-in player 
    // since 'predict_points' is run on the backend. 
    // For this POC, we'll assign a dynamic calculation based on their form:
    bp.predicted_points = bp.predicted_points || ((bp.form_avg_runs * 1) + (bp.form_avg_wickets * 25)) || 25
    
    localStorage.setItem('optimizationResults', JSON.stringify(results.value))
    squadChanged.value = true
  }
  selectedPlayerForSwap.value = null
}

onMounted(() => {
  const data = localStorage.getItem('optimizationResults')
  if (data) {
    const parsed = JSON.parse(data)
    results.value = parsed.optimal_team || parsed
    fetchInsights()
  } else {
    router.push('/')
  }
})

const fetchInsights = async () => {
  if (!results.value || !store.selectedTeamA) return
  isLoadingInsights.value = true
  insightsError.value = ''
  
  try {
    const response = await fetch('http://localhost:8000/api/insights', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        team_a: store.selectedTeamA,
        team_b: store.selectedTeamB,
        optimal_team: results.value.squad,
        all_drafted: store.draftedPlayers
      })
    })
    
    if (!response.ok) throw new Error("Failed to fetch insights")
    const data = await response.json()
    insightsReport.value = data.report
    squadChanged.value = false
  } catch (e) {
    console.error(e)
    insightsError.value = "Failed to load AI Insights. Please make sure the backend is running and the OPENAI_API_KEY is valid."
  } finally {
    isLoadingInsights.value = false
  }
}

// Quick markdown formatter for the UI
const formattedInsights = computed(() => {
  let text = insightsReport.value
  if (!text) return ''
  
  // Basic markdown to HTML
  text = text.replace(/### (.*)/g, '<h3 class="text-xl font-bold text-white mt-6 mb-2 border-b border-dark-700 pb-2">$1</h3>')
  text = text.replace(/\*\*(.*?)\*\*/g, '<strong class="text-brand">$1</strong>')
  text = text.replace(/- (.*)/g, '<li class="ml-4 list-disc">$1</li>')
  
  return text
})


const assignCaptain = (player: any) => {
  results.value.squad.forEach((p: any) => {
    if (p.id === player.id) p.is_captain = true
    else p.is_captain = false
    if (p.is_captain && p.is_vice_captain) p.is_vice_captain = false
  })
  localStorage.setItem('optimizationResults', JSON.stringify(results.value))
  selectedPlayerForSwap.value = null
  squadChanged.value = true
}

const assignViceCaptain = (player: any) => {
  results.value.squad.forEach((p: any) => {
    if (p.id === player.id) p.is_vice_captain = true
    else p.is_vice_captain = false
    if (p.is_captain && p.is_vice_captain) p.is_captain = false
  })
  localStorage.setItem('optimizationResults', JSON.stringify(results.value))
  selectedPlayerForSwap.value = null
  squadChanged.value = true
}

const totalCredits = computed(() => {
  if (!results.value) return 0
  return results.value.squad.reduce((sum: number, p: any) => sum + p.credits, 0)
})

const totalPoints = computed(() => {
  if (!results.value) return 0
  return results.value.squad.reduce((sum: number, p: any) => {
    let mult = 1
    if (p.is_captain) mult = 2
    if (p.is_vice_captain) mult = 1.5
    return sum + (p.predicted_points * mult)
  }, 0)
})

const getPlayersByRole = (role: string) => {
  if (!results.value) return []
  return results.value.squad.filter((p: any) => p.role === role)
}
</script>
